@startuml
entity Pegawai{

}

entity User{

}

entity Bagian{

}

entity Form_Cuti_Tahunan{

}

entity Jenis{

}

entity Admin_Cuti{

}

entity Status_Admin_Cuti{

}


entity Pertimbangan{

}

entity Status_Pertimbangan{

}

entity Keputusan_Pejabat{

}

@enduml